default_job = "nextest"
env.CARGO_TERM_COLOR = "always"

[jobs.clippy]
command = ["cargo", "clippy"]
need_stdout = false

[jobs.test]
command = [
    "cargo", "nextest", "run",
    "--hide-progress-bar", "--failure-output", "final"
]
env.RUSTFLAGS = "--cfg loom"
need_stdout = true
analyzer = "nextest"

[keybindings]
t = "job:test"
