[package]
name = "coro"
version = "0.1.0"
edition = "2024"

[dependencies]
libc.workspace = true
lio = { path = "../../lio" }
socket2.workspace = true
tokio = { version = "1.48.0", features = ["macros", "rt"] }
