[package]
name = "clean"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.174"
liten = { path = "../../liten", features = ["blocking", "runtime", "time"] }
socket2 = "0.6.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
