[package]
name = "testing"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
futures-util = { version = "0.3.31", features = ["io"] }
liten.path = "../../liten"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
socket2.workspace = true
libc.workspace = true
